# Generated by Django 5.0 on 2024-02-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_carttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carttable',
            name='cartstatus',
            field=models.IntegerField(null=True),
        ),
    ]
