# Generated by Django 5.0 on 2024-04-24 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_carttable_orderid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordertable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finaltotal', models.IntegerField()),
                ('paymode', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('address', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.registration')),
            ],
        ),
    ]
